I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 76, in script
    $reset_example()
  File "game/script.rpy", line 76, in <module>
    $reset_example()
NameError: name 'reset_example' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 76, in script
    $reset_example()
  File "/Users/gillian/Desktop/GNDR206/renpy-8.3.3-sdk/renpy/ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/gillian/Desktop/GNDR206/renpy-8.3.3-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 76, in <module>
    $reset_example()
NameError: name 'reset_example' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.3.24111502
WitchTrialGame 1.0
Sun Dec  8 22:08:44 2024
